# kind: Pod
# apiVersion: v1
# metadata:
#   name: go-app
#   labels:
#     app: go
# spec:
#   containers:
#   - name: go-app
#     image: kubernetes-bootcamp-go:v0.7
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
  labels:
    app: go
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
      - name: go-app
        image: kubernetes-bootcamp-go:v0.8
        resources:
          requests: 
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8090
        env:
        - name: VERSION
          value: v0.8
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8090
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 1
---
kind: Service
apiVersion: v1
metadata:
  name: go-service
spec:
  selector:
    app: go
  ports:
  # Default port used by the image
  - port: 8090
---
kind: Pod
apiVersion: v1
metadata:
  name: deno-app
  labels:
    app: deno
spec:
  containers:
  - name: deno-app
    image: kubernetes-bootcamp-deno:v0.4
---
kind: Service
apiVersion: v1
metadata:
  name: deno-service
spec:
  selector:
    app: deno
  ports:
  # Default port used by the image
  - port: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
spec:
  # ingressClassName: kong
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/go"
        backend:
          service:
            name: go-service
            port:
              number: 8090
      - pathType: Prefix
        path: "/deno"
        backend:
          service:
            name: deno-service
            port:
              number: 8000
---